# Generated by Django 1.11 on 2018-03-08 19:09

from django.db import migrations, models


def copy_last_edited(apps, schema_editor):
    """Use last_updated as the starting value for profile_last_updated."""
    Participant = apps.get_model("ws", "Participant")
    for par in Participant.objects.all():
        par.profile_last_updated = par.last_updated
        par.save()


class Migration(migrations.Migration):

    dependencies = [('ws', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='profile_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(copy_last_edited),
        migrations.AlterField(
            model_name='participant',
            name='profile_last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
