# Generated by Django 3.2.21 on 2024-01-27 20:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ws", "0001_squashed_0056_car"),
    ]

    operations = [
        # The somewhat-yearly bump of the max year, stored *in* the model. Sigh.
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(2026),
                    django.core.validators.MinValueValidator(1903),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="ws.trip"
            ),
        ),
    ]
