# Generated by Django 4.2.11 on 2024-04-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ws", "0002_car_year_and_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("retrieved_at", models.DateTimeField(auto_now=True)),
                ("response", models.JSONField(default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
