# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 23:29
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import ws.fields


class Migration(migrations.Migration):

    dependencies = [('ws', '0003_trip_wimp')]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'membership_expires',
                    models.DateField(
                        blank=True,
                        help_text='Last day that annual membership dues are valid',
                        null=True,
                    ),
                ),
                (
                    'waiver_expires',
                    models.DateField(
                        blank=True,
                        help_text='Day after which liability waiver is no longer valid',
                        null=True,
                    ),
                ),
                ('last_cached', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='membership',
            field=ws.fields.OptionalOneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='ws.Membership',
            ),
        ),
    ]
