# Generated by Django 1.11 on 2018-05-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('ws', '0004_cached_membership')]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='membership_required',
            field=models.BooleanField(
                default=True,
                help_text='Require an active MITOC membership to participate. If disabled, only waivers will be mandated.',
            ),
        )
    ]
