# Generated by Django 4.2.16 on 2024-09-07 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ws", "0004_index_on_bools"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="discounts",
        ),
        migrations.DeleteModel(
            name="Discount",
        ),
    ]
