# Generated by Django 4.2.16 on 2024-10-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ws", "0005_remove_participant_discounts_delete_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="winterschoolleaderapplication",
            name="mentorship_longevity",
            field=models.TextField(
                blank=True,
                help_text="How long are you planning stay with MITOC? No need to be exact, just a tentative timeframe which can help us pair mentors/mentees.",
                max_length=5000,
            ),
        ),
        migrations.AlterField(
            model_name="winterschoolleaderapplication",
            name="mentorship_goals",
            field=models.TextField(
                blank=True,
                help_text='What are you looking to get out of the mentorship program? Possible examples include learning how to: "lead trips in winter," "be an ice-climbing leader," "lead full C/I/S trips," or "manage group dynamics."',
                max_length=5000,
            ),
        ),
    ]
