# Generated by Django 4.2.17 on 2025-01-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ws", "0006_add_ws_application_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="description",
            field=models.TextField(
                help_text='<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown</a> supported! Please use HTTPS images sparingly, and only if properly licensed.'
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="winter_terrain_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A: <1 hour to intensive care, below treeline"),
                    ("B", "B: >1 hour to intensive care, below treeline"),
                    ("C", "C: above treeline"),
                ],
                db_index=True,
                help_text='Trip leaders must meet <a href="/help/participants/ws_ratings/" target="_blank">requirements for terrain & activity ratings</a>.',
                max_length=1,
                null=True,
                verbose_name="Terrain level",
            ),
        ),
    ]
