# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 16:44
from __future__ import unicode_literals

from django.db import migrations


def make_groups(apps, schema_editor):
    """ Create groups that are expected by the software. """
    Group = apps.get_model('auth', 'Group')

    Group.objects.get_or_create(name='leaders')
    Group.objects.get_or_create(name='users_with_info')
    Group.objects.get_or_create(name='WSC')
    Group.objects.get_or_create(name='WIMP')

    # Created based off all activites in LeaderRating.CLOSED_ACTIVITES
    # (with "WSC" being a special case for the time being)
    Group.objects.get_or_create(name='biking_chair')
    Group.objects.get_or_create(name='boating_chair')
    Group.objects.get_or_create(name='cabin_chair')
    Group.objects.get_or_create(name='climbing_chair')
    Group.objects.get_or_create(name='hiking_chair')


def do_nothing(*args):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0006_participant_gravatar_opt_out'),
    ]

    operations = [
        migrations.RunPython(make_groups, reverse_code=do_nothing,
                             hints={'model_name': 'auth_group',
                                    'target_db': 'auth_db'})

    ]
