# Generated by Django 4.2.17 on 2025-06-04 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ws", "0007_target_blank_help_links"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="requires_reimbursement",
        ),
    ]
