# Generated by Django 4.2.23 on 2025-08-26 19:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ws", "0008_remove_registration"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChairApproval",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                (
                    "trip_edit_revision",
                    models.PositiveIntegerField(
                        help_text="The version of the trip which the chair approved"
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="ws.participant"
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="ws.trip"
                    ),
                ),
            ],
        ),
    ]
