# Generated by Django 4.2.23 on 2025-08-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ws", "0009_chair_approval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="edit_revision",
            field=models.PositiveIntegerField(
                default=1,
                help_text="An incremented integer, to avoid simultaneous edits to the trip.",
            ),
        ),
    ]
