# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0009_unique_signups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='affiliation',
            field=models.CharField(choices=[('Undergraduate student', [('MU', 'MIT undergrad'), ('NU', 'Non-MIT undergrad')]), ('Graduate student', [('MG', 'MIT grad student'), ('NG', 'Non-MIT grad student')]), ('MIT', [('MA', 'MIT affiliate (staff, faculty, etc.)'), ('ML', 'MIT alum (former student)')]), ('NA', 'Non-affiliate')], max_length=2),
        ),
    ]
