# Generated by Django 4.2.23 on 2025-08-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ws", "0010_bump_default_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="chairapproval",
            name="notes",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
