# Generated by Django 4.2.23 on 2025-09-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ws", "0011_approval_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="winterschoolleaderapplication",
            name="desired_rating",
            field=models.CharField(
                help_text="The rating you believe you would be qualified for based on the criteria above",
                max_length=255,
                verbose_name="Expected rating",
            ),
        ),
        migrations.AddField(
            model_name="winterschoolleaderapplication",
            name="aspirational_rating",
            field=models.CharField(
                blank=True,
                help_text='Please share if you hope to improve your rating in a specific domain this winter (e.g. "coI interested in coleading with I to become full I and lead ice climbing trips in the future")',
                max_length=255,
                verbose_name="Aspirational rating",
            ),
        ),
        migrations.AlterField(
            model_name="winterschoolleaderapplication",
            name="taking_wfa",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("Already", "Already hold WFA or equivalent"),
                    ("No", "No"),
                    ("Maybe", "Maybe/don't know"),
                ],
                help_text="You can receive a WFA subsidy from MITOC by leading two or more trips! While WFA typically costs $250-$350, the MITOC-discounted cost is $100 for MIT students and $150 for other leaders.",
                max_length=10,
                verbose_name="Do you plan on taking a WFA course before Winter School?",
            ),
        ),
        migrations.AlterField(
            model_name="winterschoolleaderapplication",
            name="mentorship_goals",
            field=models.TextField(
                blank=True,
                help_text='For example, "learning how to lead trips in winter," "looking to become an ice climbing leader with MITOC", "skill development/support from MITOC leaders", "learning how to lead C/I/S trips, having been a B/coI/coS in the past", or "learning how to manage group dynamics."',
                max_length=5000,
                verbose_name="What are you looking to get out of the mentorship program?",
            ),
        ),
        migrations.AlterField(
            model_name="winterschoolleaderapplication",
            name="mentorship_longevity",
            field=models.TextField(
                blank=True,
                help_text="Need not be exact -- an estimate can help us pair you with a mentor/mentee",
                max_length=5000,
                verbose_name="How long are you planning to stay with MITOC?",
            ),
        ),
    ]
