# Generated by Django 4.2.23 on 2025-09-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ws", "0012_ws_application_changes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="program",
            field=models.CharField(
                choices=[
                    (
                        "Specific rating required",
                        [
                            ("biking", "Biking"),
                            ("boating", "Boating"),
                            ("cabin", "Cabin"),
                            ("climbing", "Climbing"),
                            ("hiking", "3-season hiking"),
                            ("mitoc_rock_program", "School of Rock"),
                            ("winter_school", "Winter School"),
                            ("winter_non_iap", "Winter (outside IAP)"),
                        ],
                    ),
                    (
                        "Any leader rating allowed",
                        [
                            ("circus", "Circus"),
                            ("service", "Service"),
                            ("none", "None"),
                        ],
                    ),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
    ]
