# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-02 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('ws', '0013_car_year_update')]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(
                help_text=(
                    '<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet">'
                    'Markdown'
                    '</a> supported! '
                    'Please use HTTPS images sparingly, and only if properly licensed.'
                )
            ),
        )
    ]
