# Generated by Django 4.2.23 on 2025-10-25 18:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ws", "0014_paddleboarding"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChairApprovalReminder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("biking", "Biking"),
                            ("boating", "Boating"),
                            ("cabin", "Cabin"),
                            ("climbing", "Climbing"),
                            ("hiking", "Hiking"),
                            ("winter_school", "Winter School"),
                        ],
                        max_length=31,
                    ),
                ),
                ("had_trip_info", models.BooleanField()),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="ws.trip"
                    ),
                ),
            ],
        ),
    ]
