# Generated by Django 4.2.25 on 2025-10-28 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ws", "0015_create_chair_approval_reminder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="waitlistsignup",
            # Dropped default ordering from 60a37614a2a185113f4f4e166fc50bdd7b0ec112
            options={},
        ),
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.PositiveIntegerField(
                validators=[
                    # Yearly bump of the maximum year allowed
                    django.core.validators.MaxValueValidator(2027),
                    django.core.validators.MinValueValidator(1903),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="membership_expires",
            field=models.DateField(
                blank=True,
                # Just a help text change from d69bd7dd584c9ed9b6c21c95eac9fb06361603d8
                help_text="Last day that annual dues are valid",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="send_membership_reminder",
            field=models.BooleanField(
                default=False,
                # Just a help text change from d69bd7dd584c9ed9b6c21c95eac9fb06361603d8
                help_text="MITOC cannot automatically charge you, but we can send you an email when it's time to renew.",
                verbose_name="Send annual reminder to renew dues",
            ),
        ),
    ]
