# Generated by Django 4.2.25 on 2026-04-27 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ws", "0016_missed_noop_migrations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(2028),
                    django.core.validators.MinValueValidator(1903),
                ]
            ),
        ),
    ]
