# Generated by Django 1.11.27 on 2020-01-11 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0027_update_trip_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(2022),
                    django.core.validators.MinValueValidator(1903),
                ]
            ),
        ),
    ]
