# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-11 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0028_vehicle_year_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripinfo',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
