# Generated by Django 1.11.27 on 2020-01-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0030_worry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(
                help_text='This will be shared with leaders & other participants. <a href="/accounts/email/">Manage email addresses</a>.',
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='tripinfo',
            name='drivers',
            field=models.ManyToManyField(
                blank=True,
                help_text='If a trip participant is driving, but is not on this list, they must first submit <a href="/profile/edit/#car">information about their car</a>. They should then be added here.',
                to='ws.Participant',
            ),
        ),
    ]
