# Generated by Django 1.11.27 on 2020-01-25 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0031_format_lazy_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotterySeparation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                (
                    'creator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='separations_created',
                        to='ws.Participant',
                    ),
                ),
                (
                    'initiator',
                    models.ForeignKey(
                        help_text='Participant requesting a separation',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='separations_initiated',
                        to='ws.Participant',
                    ),
                ),
                (
                    'recipient',
                    models.ForeignKey(
                        help_text='The participant with whom the initiator should not be placed on a trip',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='separations_received',
                        to='ws.Participant',
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lotteryseparation', unique_together={('initiator', 'recipient')}
        ),
    ]
