# Generated by Django 2.2.13 on 2020-10-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0032_lotteryseparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='ga_key',
            field=models.CharField(
                blank=True,
                help_text='key for Google spreadsheet with membership information (shared as read-only with the company)',
                max_length=63,
            ),
        ),
    ]
