# Generated by Django 2.2.24 on 2021-06-20 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0034_drop_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(2023),
                    django.core.validators.MinValueValidator(1903),
                ]
            ),
        ),
    ]
