# Generated by Django 3.2.7 on 2021-10-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0038_rephrase_trip_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='send_membership_reminder',
            field=models.BooleanField(
                default=False,
                help_text="MITOC cannot automatically renew memberships, but we can send you an email when it's time to renew.",
                verbose_name='Send annual reminder to renew membership',
            ),
        ),
        migrations.CreateModel(
            name='MembershipReminder',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'reminder_sent_at',
                    models.DateTimeField(
                        verbose_name='Last time an email was sent reminding this participant to renew',
                    ),
                ),
                (
                    'participant',
                    models.OneToOneField(
                        on_delete=models.deletion.CASCADE, to='ws.participant'
                    ),
                ),
            ],
        ),
    ]
