# Generated by Django 3.2.9 on 2022-01-05 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ws', '0039_send_reminder_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(2024),
                    django.core.validators.MinValueValidator(1903),
                ]
            ),
        ),
        migrations.AlterField(
            model_name='lotteryinfo',
            name='car_status',
            field=models.CharField(
                choices=[
                    ('none', 'Not driving'),
                    ('own', 'Can drive others'),
                    ('rent', 'Willing to rent'),
                    ('self', 'Can drive self'),
                ],
                default='none',
                max_length=7,
            ),
        ),
    ]
