# Generated by Django 3.2.9 on 2022-02-06 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ws', '0040_car_year_and_driving_self'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingListRequest',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('num_attempts', models.PositiveIntegerField(default=0)),
                (
                    'last_time_attempted',
                    models.DateTimeField(
                        blank=True,
                        help_text='Time at which we most recently attempted this request.',
                        null=True,
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        db_index=True,
                        help_text='Email address of the requesting user',
                        max_length=254,
                    ),
                ),
                (
                    'mailing_list',
                    models.EmailField(
                        help_text='MIT Mailman list to unsubscribe from', max_length=254
                    ),
                ),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('REQUESTED', 'Requested'),
                            ('SUCCEEDED', 'Succeeded'),
                            ('FAILED', 'Failed'),
                            ('FAILED_RETRYABLE', 'Failed, will retry later'),
                        ],
                        default='REQUESTED',
                        max_length=32,
                    ),
                ),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('SUBSCRIBE', 'Subscribe'),
                            ('UNSUBSCRIBE', 'Unsubscribe'),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    'requested_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='mailinglistrequest',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('state', 'REQUESTED'),
                    ('state', 'FAILED_RETRYABLE'),
                    _connector='OR',
                ),
                fields=('email', 'mailing_list', 'state'),
                name='one_active_request_at_a_time',
            ),
        ),
    ]
