# Generated by Django 3.2.13 on 2022-05-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0040_car_year_and_driving_self'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='program',
            field=models.CharField(
                choices=[
                    (
                        'Specific rating required',
                        [
                            ('biking', 'Biking'),
                            ('boating', 'Boating'),
                            ('cabin', 'Cabin'),
                            ('climbing', 'Climbing'),
                            ('hiking', '3-season hiking'),
                            ('mitoc_rock_program', 'School of Rock'),
                            ('winter_school', 'Winter School'),
                            ('winter_non_iap', 'Winter (outside IAP)'),
                        ],
                    ),
                    (
                        'Any leader rating allowed',
                        [
                            ('circus', 'Circus'),
                            ('service', 'Service'),
                            ('none', 'None'),
                        ],
                    ),
                ],
                default='none',
                max_length=255,
            ),
        ),
    ]
