# Generated by Django 3.2.13 on 2022-05-09 18:33

from django.db import migrations, models

import ws.utils.dates


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0041_sor_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='signups_open_at',
            field=models.DateTimeField(default=ws.utils.dates.local_now_to_the_minute),
        ),
    ]
