# Generated by Django 3.2.13 on 2022-05-18 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ws', '0043_trip_edit_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='last_updated_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='trips_updated',
                to='ws.participant',
            ),
        ),
    ]
