# Generated by Django 3.2.15 on 2022-09-18 18:34

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ws', '0044_trip_last_updated_by'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trip',
            index=django.contrib.postgres.indexes.GistIndex(
                django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.CombinedSearchVector(
                        django.contrib.postgres.search.SearchVector(
                            'name', config='english', weight='A'
                        ),
                        '||',
                        django.contrib.postgres.search.SearchVector(
                            'description', config='english', weight='B'
                        ),
                        django.contrib.postgres.search.SearchConfig('english'),
                    ),
                    '||',
                    django.contrib.postgres.search.SearchVector(
                        'prereqs', config='english', weight='B'
                    ),
                    django.contrib.postgres.search.SearchConfig('english'),
                ),
                name='search_vector_idx',
            ),
        ),
    ]
