# Generated by Django 3.2.16 on 2022-10-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0047_populate_text_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winterschoolleaderapplication',
            name='taking_wfa',
            field=models.CharField(
                choices=[
                    ('Yes', 'Yes'),
                    ('Already', 'Already hold WFA or equivalent'),
                    ('No', 'No'),
                    ('Maybe', "Maybe/don't know"),
                ],
                help_text="You can subsidize your WFA certification by $100 by leading two or more trips! "
                "MITOC holds a WFA course every fall on MIT's campus.",
                max_length=10,
                verbose_name='Do you plan on taking a WFA course before Winter School?',
            ),
        ),
        migrations.AlterField(
            model_name='winterschoolleaderapplication',
            name='training',
            field=models.TextField(
                blank=True,
                help_text="Details of any medical, technical, or leadership training and "
                "qualifications relevant to the winter environment, including WFA/WFR if "
                "previously taken. State the approximate dates of these activities. "
                "Leave blank if not applicable.",
                max_length=5000,
                verbose_name='Formal training and qualifications',
            ),
        ),
    ]
