# Generated by Django 3.2.16 on 2022-10-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ws', '0049_yoga'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='requires_reimbursement',
            field=models.BooleanField(
                default=False,
                help_text='If you have an approved budget for this trip, you must register with Atlas.',
            ),
        ),
    ]
