# Generated by Django 3.2.16 on 2022-12-04 21:38

from django.db import migrations, models


def apply_terrain_level(apps, schema_editor):
    Trip = apps.get_model('ws', 'Trip')
    Trip.objects.filter(level__contains='A').update(winter_terrain_level='A')
    Trip.objects.filter(level__contains='B').update(winter_terrain_level='B')
    Trip.objects.filter(level__contains='C').update(winter_terrain_level='C')


def reset_terrain_level(apps, schema_editor):
    Trip = apps.get_model('ws', 'Trip')
    Trip.objects.filter(winter_terrain_level__isnull=False).update(
        winter_terrain_level=None
    )


class Migration(migrations.Migration):
    dependencies = [
        ('ws', '0051_consistent_levels'),
    ]

    operations = [
        # (Just a rename of `verbose_name`)
        migrations.AlterField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(
                choices=[
                    (
                        'Biking',
                        [
                            ('biking_road', 'Road biking'),
                            ('biking_mountain', 'Mountain biking'),
                        ],
                    ),
                    (
                        'Boating',
                        [
                            ('boating_canoeing', 'Canoeing'),
                            ('boating_kayaking', 'Kayaking'),
                            ('boating_kayaking_sea', 'Sea kayaking'),
                            ('boating_surfing', 'Surfing'),
                        ],
                    ),
                    (
                        'Climbing',
                        [
                            ('climbing_bouldering', 'Bouldering'),
                            ('climbing_gym', 'Gym climbing'),
                            ('climbing_ice', 'Ice climbing'),
                            ('climbing_sport', 'Sport climbing, top rope'),
                            ('climbing_trad', 'Trad climbing'),
                        ],
                    ),
                    (
                        'Hiking',
                        [
                            ('hiking_hiking', 'Hiking'),
                            ('hiking_trail_running', 'Trail running'),
                        ],
                    ),
                    (
                        'Skiing',
                        [
                            ('skiing_bc', 'Backcountry skiing'),
                            ('skiing_xc', 'Cross-country skiing'),
                            ('skiing_resort', 'Resort skiing'),
                        ],
                    ),
                    (
                        'Miscellaneous',
                        [
                            ('ice_skating', 'Ice skating'),
                            ('ultimate', 'Ultimate'),
                            ('yoga', 'Yoga'),
                        ],
                    ),
                    (
                        'Other, N/A',
                        [('none', 'None, or not applicable'), ('other', 'Other')],
                    ),
                ],
                max_length=255,
                verbose_name='Primary trip activity',
            ),
        ),
        migrations.AddField(
            model_name='trip',
            name='winter_terrain_level',
            field=models.CharField(
                blank=True,
                choices=[
                    ('A', 'A: <1 hour to intensive care, below treeline'),
                    ('B', 'B: >1 hour to intensive care, below treeline'),
                    ('C', 'C: above treeline'),
                ],
                help_text='Trip leaders must meet <a href="/help/participants/ws_ratings/">requirements for terrain & activity ratings</a>.',
                max_length=1,
                null=True,
                verbose_name='Terrain level',
            ),
        ),
        migrations.RunPython(
            apply_terrain_level,
            reverse_code=reset_terrain_level,
        ),
    ]
