# Generated by Django 3.2.16 on 2022-12-05 18:47

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models

import ws.utils.dates


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0052_terrain_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='program',
            field=models.CharField(
                choices=[
                    (
                        'Specific rating required',
                        [
                            ('biking', 'Biking'),
                            ('boating', 'Boating'),
                            ('cabin', 'Cabin'),
                            ('climbing', 'Climbing'),
                            ('hiking', '3-season hiking'),
                            ('mitoc_rock_program', 'School of Rock'),
                            ('winter_school', 'Winter School'),
                            ('winter_non_iap', 'Winter (outside IAP)'),
                        ],
                    ),
                    (
                        'Any leader rating allowed',
                        [
                            ('circus', 'Circus'),
                            ('service', 'Service'),
                            ('none', 'None'),
                        ],
                    ),
                ],
                db_index=True,
                default='none',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(
                choices=[
                    (
                        'Biking',
                        [
                            ('biking_road', 'Road biking'),
                            ('biking_mountain', 'Mountain biking'),
                        ],
                    ),
                    (
                        'Boating',
                        [
                            ('boating_canoeing', 'Canoeing'),
                            ('boating_kayaking', 'Kayaking'),
                            ('boating_kayaking_sea', 'Sea kayaking'),
                            ('boating_surfing', 'Surfing'),
                        ],
                    ),
                    (
                        'Climbing',
                        [
                            ('climbing_bouldering', 'Bouldering'),
                            ('climbing_gym', 'Gym climbing'),
                            ('climbing_ice', 'Ice climbing'),
                            ('climbing_sport', 'Sport climbing, top rope'),
                            ('climbing_trad', 'Trad climbing'),
                        ],
                    ),
                    (
                        'Hiking',
                        [
                            ('hiking_hiking', 'Hiking'),
                            ('hiking_trail_running', 'Trail running'),
                        ],
                    ),
                    (
                        'Skiing',
                        [
                            ('skiing_bc', 'Backcountry skiing'),
                            ('skiing_xc', 'Cross-country skiing'),
                            ('skiing_resort', 'Resort skiing'),
                        ],
                    ),
                    (
                        'Miscellaneous',
                        [
                            ('ice_skating', 'Ice skating'),
                            ('ultimate', 'Ultimate'),
                            ('yoga', 'Yoga'),
                        ],
                    ),
                    (
                        'Other, N/A',
                        [('none', 'None, or not applicable'), ('other', 'Other')],
                    ),
                ],
                db_index=True,
                max_length=255,
                verbose_name='Primary trip activity',
            ),
        ),
        migrations.AlterField(
            model_name='trip',
            name='winter_terrain_level',
            field=models.CharField(
                blank=True,
                choices=[
                    ('A', 'A: <1 hour to intensive care, below treeline'),
                    ('B', 'B: >1 hour to intensive care, below treeline'),
                    ('C', 'C: above treeline'),
                ],
                db_index=True,
                help_text='Trip leaders must meet <a href="/help/participants/ws_ratings/">requirements for terrain & activity ratings</a>.',
                max_length=1,
                null=True,
                verbose_name='Terrain level',
            ),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_date',
            field=models.DateField(db_index=True, default=ws.utils.dates.nearest_sat),
        ),
        # Note: Technically a very small window for non-performant queries while we rebuild
        # but it's not in use anyway...
        migrations.RemoveIndex(
            model_name='trip',
            name='search_vector_idx',
        ),
        migrations.AddIndex(
            model_name='trip',
            index=django.contrib.postgres.indexes.GistIndex(
                django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.CombinedSearchVector(
                        django.contrib.postgres.search.CombinedSearchVector(
                            django.contrib.postgres.search.SearchVector(
                                'name', config='english', weight='A'
                            ),
                            '||',
                            django.contrib.postgres.search.SearchVector(
                                'description', config='english', weight='B'
                            ),
                            django.contrib.postgres.search.SearchConfig('english'),
                        ),
                        '||',
                        django.contrib.postgres.search.SearchVector(
                            'prereqs', config='english', weight='B'
                        ),
                        django.contrib.postgres.search.SearchConfig('english'),
                    ),
                    '||',
                    django.contrib.postgres.search.SearchVector(
                        'activity', 'trip_type', config='english', weight='C'
                    ),
                    django.contrib.postgres.search.SearchConfig('english'),
                ),
                name='search_vector_idx',
            ),
        ),
    ]
