# Generated by Django 3.2.19 on 2023-06-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ws', '0054_allow_null_reminder_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
