# Generated by Django 3.2.21 on 2023-10-02 13:42

import django.core.validators
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ws', '0055_discount_url_non_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(
                choices=[
                    ('AL', 'Alabama'),
                    ('AK', 'Alaska'),
                    ('AZ', 'Arizona'),
                    ('AR', 'Arkansas'),
                    ('CA', 'California'),
                    ('CO', 'Colorado'),
                    ('CT', 'Connecticut'),
                    ('DE', 'Delaware'),
                    ('DC', 'District of Columbia'),
                    ('FL', 'Florida'),
                    ('GA', 'Georgia'),
                    ('HI', 'Hawaii'),
                    ('ID', 'Idaho'),
                    ('IL', 'Illinois'),
                    ('IN', 'Indiana'),
                    ('IA', 'Iowa'),
                    ('KS', 'Kansas'),
                    ('KY', 'Kentucky'),
                    ('LA', 'Louisiana'),
                    ('ME', 'Maine'),
                    ('MD', 'Maryland'),
                    ('MA', 'Massachusetts'),
                    ('MI', 'Michigan'),
                    ('MN', 'Minnesota'),
                    ('MS', 'Mississippi'),
                    ('MO', 'Missouri'),
                    ('MT', 'Montana'),
                    ('NE', 'Nebraska'),
                    ('NV', 'Nevada'),
                    ('NH', 'New Hampshire'),
                    ('NJ', 'New Jersey'),
                    ('NM', 'New Mexico'),
                    ('NY', 'New York'),
                    ('NC', 'North Carolina'),
                    ('ND', 'North Dakota'),
                    ('OH', 'Ohio'),
                    ('OK', 'Oklahoma'),
                    ('OR', 'Oregon'),
                    ('PA', 'Pennsylvania'),
                    ('RI', 'Rhode Island'),
                    ('SC', 'South Carolina'),
                    ('SD', 'South Dakota'),
                    ('TN', 'Tennessee'),
                    ('TX', 'Texas'),
                    ('UT', 'Utah'),
                    ('VT', 'Vermont'),
                    ('VA', 'Virginia'),
                    ('WA', 'Washington'),
                    ('WV', 'West Virginia'),
                    ('WI', 'Wisconsin'),
                    ('WY', 'Wyoming'),
                    ('XX', 'Other (Canada, Mexico, etc.)'),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(2025),
                    django.core.validators.MinValueValidator(1903),
                ]
            ),
        ),
    ]
